name: warrier
favicon: null
layout_spectrum: 0.7442179075442255
typography_spectrum: 0.3225795980542898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5437480628024787
  lightness: 0.9779309437144548
  saturation: 0.6934966745320708
  rhythmicContrast: 0.25912084826268256
purpose: []
